/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void application_lists_refcount_dec(void *obj) ;
void application_lists_refcount_inc(void *obj) ;
void * application_lists_new(uint32_t appid, struct conf_loader *cl, const struct conf_info *info) ;

#ifdef __cplusplus
}
#endif
