/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/* Offset past conf_info_directory and '/' */
void conf_info_init(const char *confdir) ;
const char * conf_info_relative_path(const char *path) ;
void conf_info_assert_pathok(const char *path) ;
struct conf_info * conf_info_new(const struct conf_type *type, const char *name, const char *path, const struct conf_segment_ops *seg,
              uint32_t loadflags, const void *userdata, size_t userdatalen) ;
void conf_info_free(struct conf_info *info) ;
bool conf_info_ischanged(const struct conf_info *info) ;

#ifdef __cplusplus
}
#endif
