/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void conf_loader_init(struct conf_loader *cl) ;
bool conf_loader_eof(const struct conf_loader *cl) ;
int conf_loader_err(const struct conf_loader *cl) ;
bool conf_loader_open(struct conf_loader *cl, const char *fn, const char *backupdir, const char *backupsuffix, int clev, uint8_t flags) ;
const char * conf_loader_readline(struct conf_loader *cl) ;
const char * conf_loader_appendline(struct conf_loader *cl) ;
void conf_loader_unreadline(struct conf_loader *cl) ;
__attribute__((malloc)) char * conf_loader_readfile_binary(struct conf_loader *cl, size_t *len, size_t maxsz) ;
__attribute__((malloc)) char * conf_loader_readfile(struct conf_loader *cl, size_t *len, unsigned maxlines) ;
const char * conf_loader_path(const struct conf_loader *cl) ;
unsigned conf_loader_line(const struct conf_loader *cl) ;
void conf_loader_done(struct conf_loader *cl, struct conf_info *info) ;

/* @param fn File name relative to the config directory
 */
void conf_loader_reject(struct conf_loader *cl, const char *fn, const char *rejectdir) ;

/* COVERAGE EXCLUSION: Was covered by opendnscache tests */
bool conf_loader_iscompressed(struct conf_loader *cl) ;
void conf_loader_fini(struct conf_loader *cl) ;

#ifdef __cplusplus
}
#endif
