/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/**
 * Push a namespace based on a JSON object onto the per thread stack of namespaces.
 *
 * @param namespace Pointer to a namespace
 * @param object    Pointer to the JSON object that implements the namespace
 */
void crl_namespace_push_object(struct crl_namespace *namespace, cJSON *object) ;

/**
 * Push a namespace based on a CRL attribute set onto the per thread stack of namespaces.
 *
 * @param namespace  Pointer to a namespace
 * @param attributes Pointer to the CRL attributes set that implements the namespace
 */
void crl_namespace_push_attributes(struct crl_namespace *namespace, struct crl_value *attributes) ;

/**
 * Pop the top namespace off the per thread stack of namespaces.
 *
 * @return the namespace popped or NULL if the stack was empty
 */
struct crl_namespace * crl_namespace_pop(void) ;

/**
 * Look up a name in the per thread stack of namespaces.
 *
 * @param name Pointer to the name to look up
 * @param len  Length of the name
 *
 * @return The matching JSON value from the first matching namespace or NULL if the name wasn't found in any namespace
 */
cJSON * crl_namespace_lookup(const char *name, unsigned len) ;

#ifdef __cplusplus
}
#endif
