/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/**
 * Set the options for storing digests. May be called dynamically to update the options.
 *
 * @param dir        Name of the directory in which to store the digests
 * @param freq       Update frequency in seconds
 * @param maxage     Maximum age in seconds
 */
void digest_store_set_options(const char *dir, unsigned freq, unsigned maxage) ;
void digest_store_changed(const struct confset *conf) ;
void digest_store_unchanged(const struct confset *conf) ;

#ifdef __cplusplus
}
#endif
