/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void domaintagging_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct domaintagging * domaintagging_conf_get(const struct confset *set, module_conf_t m) ;
bool domaintagging_match(const struct domaintagging *me, pref_categories_t *all_categories, const uint8_t *name, struct xray *x, const char *listname) ;
struct domaintagging * domaintagging_new(struct conf_loader *cl) ;

#ifdef __cplusplus
}
#endif
