/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void geoip_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct geoip * geoip_conf_get(const struct confset *set, module_conf_t m) ;
const char * geoip_cc(const struct geoip *me, const struct netaddr *addr, uint32_t *region) ;

#ifdef __cplusplus
}
#endif
