/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/**
 * Load a JSON file
 *
 * @param me     A json_file structure to populate
 * @param cl     A conf loader of a JSON file containg a JSON object
 * @param type   The type name expected in the JSON object, whose value is the data
 * @param member If the actual JSON object is nested inside a JSON object that isn't wanted, the member name, else NULL.
 */
bool json_file_load(struct json_file *me, struct conf_loader *cl, const char *type, const char *member) ;
void json_file_fini(struct json_file *me) ;

#ifdef __cplusplus
}
#endif
