/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


// This helper function is global because it's used by opendnscache specific optcfg functions

bool key_value_text_to_longlong(struct key_value_source *ctx, void *var, const char *value, size_t value_len,    /* COVERAGE EXCLUSION: Was covered by opendnscache tests */
                           const struct key_value_attrs *params, int base) ;
bool key_value_text_to_uint8(struct key_value_source *ctx, void *var, const char *value, size_t value_len,    /* COVERAGE EXCLUSION: Was covered by opendnscache tests */
                        const struct key_value_attrs *params) ;
void key_value_uint8_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v,    /* COVERAGE EXCLUSION: Was covered by opendnscache tests */
                       const char *fmt, ...)) ;

/* COVERAGE EXCLUSION: Was covered by opendnscache tests */
bool key_value_text_to_unsigned(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_unsigned_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;

/* COVERAGE EXCLUSION: Was covered by opendnscache tests */
bool key_value_text_to_uint16(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_uint16_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_uint32(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_uint32_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_int(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_int_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_hex(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_hex_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_dnsname(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_dnsname_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_ip(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_ip4_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
void key_value_ip6_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_encapip(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_encapip_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_ipport(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_ipport_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;

/* COVERAGE EXCLUSION: Was covered by opendnscache tests */
bool key_value_text_to_string(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_string_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;

/* COVERAGE EXCLUSION: Was covered by opendnscache tests */
bool key_value_text_to_domainlist(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_domainlist_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_cidrlist(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_cidrlist_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;
bool key_value_text_to_categories(struct key_value_source *ctx, void *var, const char *value, size_t value_len, const struct key_value_attrs *params) ;
void key_value_categories_format(const char *key, const void *val, void *v, __printflike(3, 4) size_t (*cb)(const char *key, void *v, const char *fmt, ...)) ;

#ifdef __cplusplus
}
#endif
