/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/**
 * This variant is for the resolver. When netprefs no longer contain CIDRs, remove LOADFLAGS_FP_ALLOW_OTHER_TYPES.
 */
void netprefs_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;

/**
 * This variant is probably not used. It replaces "netprefs_register_allow_junk_domains".
 */
void netprefs_register_just_cidr(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct netprefs * netprefs_conf_get(const struct confset *set, module_conf_t m) ;
int netprefs_get(pref_t *pref, const struct netprefs *me, const char *name, const struct netaddr *addr, struct xray *x, const char *hint) ;

/* XXX: This should go when HardCIDR stops needing it */
bool netprefs_get_policy(const struct netprefs *me, pref_t *pref, actype_t actype, uint32_t orgid, uint32_t id) ;
const struct preforg * netprefs_org(const struct netprefs *me, uint32_t id) ;
struct netprefs * netprefs_new(struct conf_loader *cl, unsigned loadflags) ;
void netprefs_refcount_inc(struct netprefs *me) ;
void netprefs_refcount_dec(struct netprefs *me) ;
const struct prefblock * netprefs_get_prefblock(const struct netprefs *me, uint32_t orgid) ;

#ifdef __cplusplus
}
#endif
