/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void networks_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct networks * networks_conf_get(const struct confset *set, module_conf_t m) ;
const struct network * networks_get(const struct networks *me, const struct netaddr *addr, struct xray *x) ;
struct networks * networks_new(struct conf_loader *cl) ;

#ifdef __cplusplus
}
#endif
