/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

const char * segment_state_to_str(enum segment_state state) ;
struct preffile * preffile_copy(const struct preffile *me) ;
void preffile_free(struct preffile *me) ;
struct pref_segments * pref_segments_new(const char *path) ;
void pref_segments_free(struct pref_segments *me) ;
bool pref_segments_ischanged(struct pref_segments *me) ;
const struct preffile * pref_segments_changed(struct pref_segments *me) ;
bool pref_segments_setpath(struct pref_segments *me, const char *path) ;
void pref_segments_retry(struct pref_segments *me, const struct preffile *pf, unsigned timeout) ;

#ifdef __cplusplus
}
#endif
