/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

unsigned prefs_org_slot(struct prefs_org *const *const me, uint32_t id, unsigned count) ;
bool prefs_org_valid(struct prefs_org *me, const char *path) ;
void prefs_org_refcount_dec(void *obj) ;
void prefs_org_refcount_inc(void *obj) ;

/*
 * Insert or replace an org in the org array.
 */
bool prefs_org_fill_slot(struct prefs_org *po, struct prefs_org **org, unsigned *count, unsigned slot, uint64_t *alloc) ;

#ifdef __cplusplus
}
#endif
