/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

const char * rr_type_to_str(rr_type_t type) ;
char * rr_type_to_buf(rr_type_t type, char *buf, size_t bufsz) ;
rr_type_t rr_type_from_str(const char *txt) ;

#ifdef __cplusplus
}
#endif
