/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void rule_init(struct rule *rule) ;
void rule_fini(struct rule *rule) ;

#ifdef __cplusplus
}
#endif
