/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void siteprefs_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct siteprefs * siteprefs_conf_get(const struct confset *set, module_conf_t m) ;

/* Lookup a preference based on the IDs passed along from the forwarder.
 */
bool siteprefs_get(pref_t *pref, const struct siteprefs *me, struct odns *odns, struct oolist **other_origins, struct xray *x) ;
const struct preforg * siteprefs_org(const struct siteprefs *me, uint32_t id) ;
struct siteprefs * siteprefs_new(struct conf_loader *cl, unsigned loadflags) ;
void siteprefs_refcount_inc(struct siteprefs *me) ;
void siteprefs_refcount_dec(struct siteprefs *me) ;
const struct prefblock * siteprefs_get_prefblock(const struct siteprefs *me, uint32_t orgid) ;

#ifdef __cplusplus
}
#endif
