/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void uint32list_refcount_dec(struct uint32list *me) ;
void uint32list_refcount_inc(struct uint32list *me) ;
struct uint32list * uint32list_new(const char *txt, struct object_fingerprint *of) ;

#ifdef __cplusplus
}
#endif
