/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

bool cidrprefs_slotisempty(const struct conf *base, unsigned slot) ;
void cidrprefs_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct cidrprefs * cidrprefs_conf_get(const struct confset *set, module_conf_t m) ;
const struct prefblock * cidrprefs_get_prefblock(const struct cidrprefs *me, uint32_t orgid) ;

/* Lookup cidrprefs by its org and bundle id */
bool cidrprefs_get_policy(const struct cidrprefs *me, pref_t *pref, uint32_t orgid, uint32_t bundleid) ;

#ifdef __cplusplus
}
#endif
