/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void * cidrprefs_org_new(uint32_t orgid, struct conf_loader *cl, const struct conf_info *info) ;

#ifdef __cplusplus
}
#endif
