/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

const char * cloudprefs_org_key_to_str(struct fileprefs *fp, unsigned i) ;
void * cloudprefs_org_new(uint32_t originid, struct conf_loader *cl, const struct conf_info *info) ;

/*
 * Lookup a preference based on the origin id (from the EDNS0 IDs).
 */
const char * cloudprefs_org_get(pref_t *pref, const struct prefs_org *me, const char *name, uint32_t origin_id, struct oolist **other_origins, struct xray *x) ;

#ifdef __cplusplus
}
#endif
