/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

bool cloudprefs_slotisempty(const struct conf *base, unsigned slot) ;
void cloudprefs_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
void cloudprefs_register_add_cidr(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct cloudprefs * cloudprefs_conf_get(const struct confset *set, module_conf_t m) ;
const struct prefblock * cloudprefs_get_prefblock(const struct cloudprefs *me, uint32_t orgid) ;

/*
 * Lookup a preference based on the EDNS0 IDs.
 */
bool cloudprefs_get(pref_t *pref, const struct cloudprefs *me, const char *name, uint32_t org_id, uint32_t origin_id, struct oolist **other_origins,
               struct xray *x) ;

#ifdef __cplusplus
}
#endif
