/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

struct conf_meta * conf_meta_new(struct conf_loader *cl, unsigned lines) ;
void conf_meta_free(struct conf_meta *me) ;

#ifdef __cplusplus
}
#endif
