/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/*
 * If multiple dispatch locks are to be held, then they must be taken in this
 * order to avoid deadlock:
 *   - todo -> live -> done
 *                  -> dead (done and dead are currently never mutually held)
 *   - wait (wait currently never held with others)
 */
void conf_dispatch_put(struct conf_dispatch *cd, enum conf_dispatch_queue queue) ;
bool conf_dispatch_getresult(struct conf_dispatch *cd, bool (*block_check_under_spinlock)(void)) ;
bool conf_dispatch_getwait(struct conf_dispatch *cd, uint64_t *min_ms) ;
conf_dispatch_handle_t conf_dispatch_getwork(struct conf_dispatch *cd, bool block) ;
void conf_dispatch_deadwork(conf_dispatch_handle_t job) ;
void conf_dispatch_donework(struct conf_dispatch *cd, conf_dispatch_handle_t job) ;

/* Return an active job from the live queue to the todo queue */
void conf_dispatch_requeue(struct conf_dispatch *cd, conf_dispatch_handle_t job) ;
void conf_dispatch_purge(void (*cb)(struct conf_dispatch *cd)) ;

#ifdef __cplusplus
}
#endif
