/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void conf_segment_init(struct conf_segment *me, uint32_t id, struct conf_loader *cl, bool failed) ;
unsigned conf_segment_slot(void *const *const me, uint32_t id, unsigned count, unsigned csoffset) ;

#ifdef __cplusplus
}
#endif
