/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void crl_source_init(struct crl_source *source, char *string, const char *file, unsigned line, unsigned version) ;
char * crl_source_skip_char(struct crl_source *source) ;
char * crl_source_skip_space(struct crl_source *source) ;
bool crl_source_is_exhausted(struct crl_source *source) ;

#ifdef __cplusplus
}
#endif
