/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void devices_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct devices * devices_conf_get(const struct confset *set, module_conf_t m) ;
const struct device * devices_get(const struct devices *me, const struct kit_deviceid *device_id, struct xray *x) ;
struct devices * devices_new(struct conf_loader *cl) ;

#ifdef __cplusplus
}
#endif
