/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

bool dirprefs_slotisempty(const struct conf *base, unsigned slot) ;
void dirprefs_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct dirprefs * dirprefs_conf_get(const struct confset *set, module_conf_t m) ;
const struct prefblock * dirprefs_get_prefblock(const struct dirprefs *me, uint32_t orgid) ;

/*
 * Lookup a preference based on the IDs passed along from the forwarder.
 */
bool dirprefs_get(pref_t *pref, const struct dirprefs *me, const struct odns *odns, struct oolist **other_origins, enum dirprefs_type *type, struct xray *x) ;

#ifdef __cplusplus
}
#endif
