/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void * dirprefs_org_new(uint32_t orgid, struct conf_loader *cl, const struct conf_info *info) ;

/*
 * Lookup a preference based on the IDs passed along from the forwarder.
 */
const char * dirprefs_org_get(pref_t *pref, const struct prefs_org *me, const struct odns *odns, struct oolist **other_origins, enum dirprefs_type *type, struct xray *x) ;

#ifdef __cplusplus
}
#endif
