/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/**
 * Allocate, initialize, and load a configuration structure of the type defined by the key_value_entry parameters
 *
 * @return A pointer to the 'struct conf' embedded in the configuration structure.
 */
struct conf * key_value_config_new(struct conf_loader *cl,
                     size_t config_size,
                     size_t conf_offset,
                     const void *defaults,
                     const struct key_value_entry *config,
                     const unsigned config_entries,
                     const struct conf_type *kv_ct,
                     void (*pre_fn)(void *),
                     bool (*post_fn)(void *, struct conf_loader *)) ;

#ifdef __cplusplus
}
#endif
