/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


// Currently, there is only one registration function

void lists_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct lists * lists_conf_get(const struct confset *set, module_conf_t m) ;

/**
 * @return A pointer to the lists_org in 'me' with 'orgid', or NULL if not found.
 */
struct lists_org * lists_find_org(const struct lists *me, uint32_t orgid) ;

#ifdef __cplusplus
}
#endif
