/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void namelist_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct namelist * namelist_conf_get(const struct confset *set, module_conf_t m) ;
bool namelist_prefix_match(const struct namelist *me, const uint8_t *name) ;

#ifdef __cplusplus
}
#endif
