/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

bool netaddr_equal(const struct netaddr *a1, const struct netaddr *a2) ;
bool netsock_fromsockaddr(struct netsock *n, const struct sockaddr *sa, socklen_t sa_len) ;
uint32_t netaddr_hash32(const struct netaddr *a) ;
uint32_t netaddr_fingerprint_bit(const struct netaddr *a) ;
struct netaddr * netaddr_from_str(struct netaddr *a, const char *str, sa_family_t family) ;
const char * netaddr_to_buf(const struct netaddr *a, char *buf, size_t sz) ;
const char * netaddr_to_str(const struct netaddr *a) ;
bool netaddr_within_mask(const struct netaddr *n1, const struct netaddr *n2, unsigned bits) ;
void netsock_init(struct netsock *me, sa_family_t family, const void *addr, in_port_t port) ;
socklen_t netsock_to_sockaddr(const struct netsock *n, void *sockaddr, socklen_t sockaddr_len) ;
const char * netsock_to_str(const struct netsock *netsock) ;
struct netsock * netsock_from_str(struct netsock *ns, const char *str, unsigned default_port) ;

#ifdef __cplusplus
}
#endif
