/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

struct object_hash * object_hash_new(unsigned rows, unsigned locks, unsigned magic) ;
unsigned object_hash_magic(struct object_hash *oh) ;
unsigned object_hash_entries(struct object_hash *oh) ;
const void * object_hash_extras(struct object_hash *oh) ;
void object_hash_free(struct object_hash *oh) ;
void * object_hash_action(struct object_hash *oh, const uint8_t *fp, unsigned fplen, bool (*action)(void *udata, void **obj), void *udata) ;
void * object_hash_add(struct object_hash *oh, void *obj, const uint8_t *fp, unsigned fplen) ;

#ifdef __cplusplus
}
#endif
