/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Create an oolist entry from a pref structure
 */
bool oolist_add(struct oolist **list, pref_t *pref, enum origin_src src) ;
void oolist_clear(struct oolist **list) ;
void oolist_rm(struct oolist **list, uint32_t origin) ;
enum origin_src oolist_origin2src(struct oolist **list, uint32_t origin) ;
const char * oolist_to_buf(const struct oolist *list, char *buf, size_t bufsz, size_t *len_out, unsigned flags) ;
const struct oolist_entry * oolist_entry(const struct oolist *list, size_t n) ;
bool oolist_check_flags(struct oolist **list, uint8_t flags) ;

#ifdef __cplusplus
}
#endif
