/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

struct osversion_current * osversion_current_new(struct conf_loader *cl) ;

/**
 * Register an osversion-current file with the conf system
 *
 * @param m       Pointer to the module identifier for the policy directory
 * @param name    Name of the policy (e.g. rules for umbrella unified policy, rules-auth-latitude for posture policy)
 * @param fn      File name pattern containing a %u to be replaced by the org id
 * @param filter  Unused filter parameter
 */
void osversion_current_register(module_conf_t *m, const char *name, const char *fn, const char *filter) ;
const struct osversion_current * osversion_current_conf_get(const struct confset *set, module_conf_t m) ;
const cJSON * osversion_current_get_data(const struct osversion_current *me) ;

#ifdef __cplusplus
}
#endif
