/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif


/**
 * Register a policy directory with the conf system
 *
 * @param m      Pointer to the module identifier for the policy directory
 * @param name   Name of the policy (e.g. rules for umbrella unified policy, rules-auth-latitude for posture policy)
 * @param fn     File name pattern containing a %u to be replaced by the org id
 * @param filter NULL or a string which will be used to filter the rules; currently, it is a prefix
 */
void policy_register(module_conf_t *m, const char *name, const char *fn, const char *filter) ;
const struct policy * policy_conf_get(const struct confset *set, module_conf_t m) ;

/**
 * @return A pointer to the policy_org in 'me' with 'orgid', or NULL if not found.
 */
struct policy_org * policy_find_org(const struct policy *me, uint32_t orgid) ;

#ifdef __cplusplus
}
#endif
