/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

bool prefixtree_walk(struct prefixtree *me, bool (*callback)(const uint8_t *, uint8_t, void *, void *), uint8_t *key,
                unsigned *key_len, void *userdata) ;
void prefixtree_delete(struct prefixtree *me, void (*callback)(void *)) ;
void * prefixtree_get(struct prefixtree *me, const uint8_t *key, int len) ;
struct prefixtree * prefixtree_new(void) ;
void ** prefixtree_put(struct prefixtree *me, const uint8_t *key, int len) ;
void * prefixtree_prefix_choose(struct prefixtree *me, const uint8_t *key, int *len, void *(*choose)(void *, void *), void *userdata) ;
bool prefixtree_contains_subtree(struct prefixtree *me, const uint8_t *key, int len) ;

#ifdef __cplusplus
}
#endif
