/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void pref_overloads_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct pref_overloads * pref_overloads_conf_get(const struct confset *set, module_conf_t m) ;
const struct overloaded_pref * pref_overloads_default_listener(const struct pref_overloads *me) ;
const struct overloaded_pref * pref_overloads_byip(const struct pref_overloads *me, const struct netaddr *addr) ;
const struct overloaded_pref * pref_overloads_bycc(const struct pref_overloads *me, const char country_code[3], uint32_t region) ;

#ifdef __cplusplus
}
#endif
