/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

void query_handling_set_allowlisted_txt(void (*update), int generation, const char *text) ;
const uint8_t * query_handling_label(int handling) ;
const char * query_handling_str(int handling) ;

#ifdef __cplusplus
}
#endif
