/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

char * sockaddr_to_buf(const struct sockaddr *sa, char *buf, size_t size, size_t *len_out) ;
bool sockaddr_sscan(const char *str, in_port_t default_port, struct sockaddr *sa, socklen_t *sockaddr_len) ;

#ifdef __cplusplus
}
#endif
