/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

URL_NORM_RETURN url_normalize(const char *url, unsigned url_len, char *buf, unsigned *buf_len) ;

#ifdef __cplusplus
}
#endif
