/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

bool urlprefs_slotisempty(const struct conf *base, unsigned slot) ;
void urlprefs_register(module_conf_t *m, const char *name, const char *fn, bool loadable) ;
const struct urlprefs * urlprefs_conf_get(const struct confset *set, module_conf_t m) ;
const struct prefblock * urlprefs_get_prefblock(const struct urlprefs *me, uint32_t orgid) ;

/* Lookup urlprefs by its org and bundle id */
bool urlprefs_get_policy(const struct urlprefs *me, pref_t *pref, uint32_t orgid, uint32_t bundleid) ;

#ifdef __cplusplus
}
#endif
