/*
 * Generated by genxface.pl - DO NOT EDIT OR COMMIT TO SOURCE CODE CONTROL!
 */
#ifdef __cplusplus
extern "C" {
#endif

bool xray_init_for_client(struct xray *x, uint16_t size) ;
void xray_fini_for_client(struct xray *x) ;
bool xraying_for_client(const struct xray *x) ;
bool xray_init_for_log(struct xray *x) ;
void xray_fini(struct xray *x) ;

/* Lines are appended into a fixed size buffer */
__printflike(3, 4) void xray(struct xray *x, unsigned n, const char *fmt, ...) ;
void xray_long_line(struct xray *x, const char *prefix1, const char *prefix2, const char *data) ;

#ifdef __cplusplus
}
#endif
